language: ruby

jdk: oraclejdk8

addons:
  code_climate:
    repo_token:
      secure: "opE/ZhRzsEU2Fn6YEnItMD/rMs3O2OHVYQQ7Ly0dAkIc9ZrVMa//ogt4k7h0QGZUettRVV7kawCtRzde+QbOmezTRwWqQJ7Mi6D6qfwlYMz+D9FcufHaCJyLy+dYeBuQqr1d6n/3gVqVGh8MAMGHipYodudCub38DQ1sVWcCMDNNo4PMRFLS0pS839SC80HAS7tutOeaeohRc+Ct5yoY2ZDoTuGtNeJhwqmDAo13RwvVu9aZw97EZPvt8UcaW5oYDnx47kDpKi4XGrTPaWpSm/IitwW11FF+Kevt0RpUS0uVWqg4/6xTjDg++ETG+94ePYrOZGF4ne/CPtC0AtaWF1jgSlL9iu4IR/Awt+2BqawKzCnoSRgCGIHRZApErC3KacadJBaPCrKwf4xxxqRXex4lXcptKRygkG4ic2r+MblyPPwIsc1Wb1QYCeVjIEGWzOgKVEUpT8qN0DAj6KQe/HuyuXKE/FiPIRfkJkRY5oGCNZtzeCzXlC+IqhZYCg6HwcZuk3CbcxRrg5VFKDlL0VWacD/FQoGgfTp3SUmaL6NMcCKSrL0vjEgx98/yM9rsGZlZOU9ioN93PQVgqpI5dl+nm9vKkFyuzW07nNM+/6PNdHbbZBY1OLNd3RSpWVC9TDtZ3Q2gAx25+31TDzD2/3yjJjfdtwIH3bdyrO44MK8="
notifications:
  slack:
    secure: cAAHcb/HdJK6elr6gfxlotUJdZys8nA/BUb1rKVt7T7EShOjqNOwHo0vZBG5fXQEbUJjHCFAl8tH1N8wz+KLoVErlMmD2OgBKGgvgm3fddkIgGRRvxe8yB0yEFy5yuvfgqJDlwPHZxbwj2Ddb8uTaLd8yzmRzGWNwLyRQTDaQbaKBaB+emP2t/1AilQHyItN02NuW3qcEGr7Hzg+IsKabDRzhMi89RV0xk2eP5iWTYW76ULbbfP3NqBpcVLskAqVQd1YOFUSEb2fdzRj7UuLUUp3C0Kb5gKfXPHb97XuMqwyviakTr02omdaM82NvB8GKn7QKBbcwA1Iz1euinxQQ7MTzJe8wLMH8q205lTpl96CANKwIxrk/HestgEboq97xSp5Wc1Qn1ynnrLOvBYW7EG/e6exguojQmkLkV9P6LW9g4nYsR8UEjyuRd252xch4+b4M3lxtlAXtpWguPfm5ZKhICBsJMlYm6//q1cBlNUOzR0cufCHDTNdlB/YLynvdg1ykFISYARP+5sV2YM9rD/1Rs/396qYr0mNbCh83P9GlZ5NZtWLQePJroHe3iQ18X3YHEcb50OTfRmKNoXTldQBD9iKNkwlFpWfruVdBWT+JRM77+yIV9ORjY7UE4ZtH8HxAg4bX+ey+C5axgxQk569h3CdLmVapFt6wovCSVk=

before_install:
  - |
    # Currently, Travis can't treat jruby 9.0.1.0
    if [[ ${TRAVIS_RUBY_VERSION} = "jruby-9.0.0.0" ]];then
      rvm get head
      rvm use jruby-9.0.1.0 --install
      ruby -v
    fi

rvm:
  - jruby-19mode
  - jruby-9.0.0.0

gemfile:
  - gemfiles/embulk-0.6.0-latest
  - gemfiles/embulk-0.6.16
  - gemfiles/embulk-0.6.17
  - gemfiles/embulk-0.6.18
  - gemfiles/embulk-0.6.19
  - gemfiles/embulk-0.6.20
  - gemfiles/embulk-0.6.21
  - gemfiles/embulk-0.6.22
  - gemfiles/embulk-0.6.23
  - gemfiles/embulk-0.6.24
  - gemfiles/embulk-0.6.25
  - gemfiles/embulk-0.6.26
  - gemfiles/embulk-0.6.27
  - gemfiles/embulk-0.7.0
  - gemfiles/embulk-0.7.0-latest
  - gemfiles/embulk-0.7.1
  - gemfiles/embulk-0.7.2
  - gemfiles/embulk-0.7.3
  - gemfiles/embulk-0.7.4
  - gemfiles/embulk-0.7.5
  - gemfiles/embulk-latest

matrix:
  exclude:
    - jdk: oraclejdk8 # Ignore all matrix at first, use `include` to allow build
  include:
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.0-latest}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.13}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.14}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.15}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.16}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.17}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.18}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.19}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.20}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.21}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.22}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.23}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.24}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.25}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.26}
    - {rvm: jruby-19mode, gemfile: gemfiles/embulk-0.6.27}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.7.0}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.7.0-latest}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.7.1}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.7.2}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.7.3}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.7.4}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.7.5}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-latest}
 allow_failures:
    - gemfile: gemfiles/embulk-0.6.22
    - gemfile: gemfiles/embulk-0.7.0
    - gemfile: gemfiles/embulk-0.7.1
    # Ignore failure for *-latest
    - gemfile: embulk-0.6.0-latest
    - gemfile: embulk-0.7.0-latest
    - gemfile: embulk-latest
