language: ruby

jdk: oraclejdk8
sudo: false

addons:
  code_climate:
    repo_token:
      secure: "opE/ZhRzsEU2Fn6YEnItMD/rMs3O2OHVYQQ7Ly0dAkIc9ZrVMa//ogt4k7h0QGZUettRVV7kawCtRzde+QbOmezTRwWqQJ7Mi6D6qfwlYMz+D9FcufHaCJyLy+dYeBuQqr1d6n/3gVqVGh8MAMGHipYodudCub38DQ1sVWcCMDNNo4PMRFLS0pS839SC80HAS7tutOeaeohRc+Ct5yoY2ZDoTuGtNeJhwqmDAo13RwvVu9aZw97EZPvt8UcaW5oYDnx47kDpKi4XGrTPaWpSm/IitwW11FF+Kevt0RpUS0uVWqg4/6xTjDg++ETG+94ePYrOZGF4ne/CPtC0AtaWF1jgSlL9iu4IR/Awt+2BqawKzCnoSRgCGIHRZApErC3KacadJBaPCrKwf4xxxqRXex4lXcptKRygkG4ic2r+MblyPPwIsc1Wb1QYCeVjIEGWzOgKVEUpT8qN0DAj6KQe/HuyuXKE/FiPIRfkJkRY5oGCNZtzeCzXlC+IqhZYCg6HwcZuk3CbcxRrg5VFKDlL0VWacD/FQoGgfTp3SUmaL6NMcCKSrL0vjEgx98/yM9rsGZlZOU9ioN93PQVgqpI5dl+nm9vKkFyuzW07nNM+/6PNdHbbZBY1OLNd3RSpWVC9TDtZ3Q2gAx25+31TDzD2/3yjJjfdtwIH3bdyrO44MK8="

before_install:
  - rvm list
  - |
    # Currently, Travis can't treat jruby 9.0.5.0
    ruby -v
    rvm get head
    rvm use jruby-9.0.5.0 --install
    gem install bundler
    ruby -v
  - gem i bundler

rvm:
  - jruby-9.0.5.0

gemfile:
  - gemfiles/embulk-0.8.0-latest
  - gemfiles/embulk-0.8.6
  - gemfiles/embulk-latest

matrix:
  allow_failures:
    # Ignore failure for *-latest
    - gemfile: embulk-0.8.0-latest
    - gemfile: embulk-latest
    
